### PR TITLE
Fixed Bug

### PR DESCRIPTION
**Pull request by gkanishk**
Fixed the bug due to which original list was not updated and the user was allowed to use delete function only once.
added 
allExpenses = [...newArr];
which copies the value of an array to other and changed the datatype of the array from const to var.

### CODE REVIEW

**Comment by tanaypratap** [comment]
thanks for the PR dude. why is the diff so big? This will confuse people who are following the course online.

**Comment by gkanishk** [comment]
I added only one line of code this might be due to change in the indentation.
The think clicked my mind that previous array was not updated so I used
allExpenses = [...newArr];
for the same and const datatype was not working so changed it to var.

**Comment by gkanishk** [comment]
You can add a new video on youtube be 16th one which would be about this

**Comment by gkanishk** [comment]
Now the diff shows only the changes, previously the problem was due to change in indentation as I used vscode to edit.

**Comment by gkanishk** [comment]
@tanaypratap there was a small bug while updating of data, I did the fix before so here's the code.

**Pull request closed without merging**
